# Generated by Django 3.2 on 2021-05-05 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RDLG_ID', models.CharField(max_length=255)),
                ('RDLG_REG_NO', models.CharField(max_length=255)),
                ('RDLG_NAME', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please enter valid name', regex='^[a-zA-Z ]+$')])),
                ('RDLG_TYPE', models.CharField(max_length=255)),
                ('TIME', models.DateTimeField(auto_now=True)),
                ('TECHNICIAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician.technician')),
            ],
            options={
                'db_table': 'Radiologist',
            },
        ),
        migrations.CreateModel(
            name='RadiologistReportMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RDLG_RPT_ID', models.CharField(max_length=255)),
                ('RP_STATUS', models.IntegerField()),
                ('FINDINGS', models.TextField(max_length=255)),
                ('IMPRESSIONS', models.TextField(max_length=255)),
                ('TIME', models.DateTimeField(auto_now=True)),
                ('RADIOLOGIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiologist.radiologist')),
                ('REPORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'db_table': 'Radiologist Report Map',
            },
        ),
        migrations.CreateModel(
            name='RadiologistReportFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RDLG_RPT_FILE_ID', models.CharField(max_length=255)),
                ('RDLG_RPT_FILE', models.ImageField(max_length=255, upload_to='radiologist_report')),
                ('TIME', models.DateTimeField(auto_now=True)),
                ('REPORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'db_table': 'Radiologist Report Files',
            },
        ),
        migrations.CreateModel(
            name='RadiologistPmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RDLG_PMT_ID', models.CharField(max_length=255)),
                ('RDLG_PMT_AMT', models.CharField(max_length=255)),
                ('TIME', models.DateTimeField(auto_now=True)),
                ('RADIOLOGIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiologist.radiologist')),
            ],
            options={
                'db_table': 'Radiologist Pmt',
            },
        ),
    ]
