# Generated by Django 3.2 on 2021-05-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiologist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='radiologistpmt',
            table='Radiologist Payment',
        ),
    ]
