# Generated by Django 3.2 on 2021-05-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('radiologist', '0003_auto_20210506_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologistreportmap',
            name='RP_STATUS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.reportstatus'),
        ),
    ]
