# Generated by Django 3.1 on 2021-05-24 12:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUPER_ID', models.CharField(max_length=255)),
                ('SUPER_NAME', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please enter valid name', regex='^[a-zA-Z ]+$')])),
                ('SUPER_MOB', models.CharField(max_length=12)),
                ('SUPER_EMAIL', models.EmailField(max_length=255)),
                ('SUPER_PASSWORD', models.CharField(max_length=255)),
                ('TIME', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Super',
            },
        ),
        migrations.CreateModel(
            name='SuperLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SESSION_ID', models.CharField(max_length=255)),
                ('LOGIN_DATETIME', models.DateTimeField()),
                ('LOGOUT_DATETIME', models.DateTimeField(blank=True, null=True)),
                ('SUPER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.super')),
            ],
            options={
                'db_table': 'Super Login',
            },
        ),
    ]
