# Generated by Django 3.2 on 2021-05-05 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TECH_ID', models.CharField(max_length=255)),
                ('TECH_NAME', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please enter valid name', regex='^[a-zA-Z ]+$')])),
                ('TECH_MOB', models.CharField(max_length=12)),
                ('TECH_EMAIL', models.EmailField(max_length=255)),
                ('TECH_PASSWORD', models.CharField(max_length=255)),
                ('TECH_IMG', models.ImageField(upload_to='technician_profile_pic')),
                ('TECH_ADDRESS', models.TextField(max_length=255)),
                ('TIME', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Technician',
            },
        ),
        migrations.CreateModel(
            name='TechnicianLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SESSION_ID', models.CharField(max_length=255)),
                ('LOGIN_DATETIME', models.DateTimeField()),
                ('LOGOUT_DATETIME', models.DateTimeField(blank=True, null=True)),
                ('TECHNICIAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician.technician')),
            ],
            options={
                'db_table': 'Technician Login',
            },
        ),
    ]
