# Generated by Django 3.2 on 2021-05-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='TECH_STATUS',
            field=models.CharField(default='Inactive', max_length=50),
        ),
    ]
