# Generated by Django 3.2 on 2021-05-05 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RP_ID', models.CharField(max_length=255)),
                ('RP_REG_NO', models.CharField(max_length=255)),
                ('RP_DATE', models.DateTimeField(auto_now=True)),
                ('RP_TIME', models.DateTimeField(auto_now=True)),
                ('RP_PRIORITY', models.CharField(max_length=255)),
                ('RP_REMARKS', models.TextField(max_length=255)),
                ('TIME', models.DateTimeField(auto_now=True)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'Report',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TKT_ID', models.CharField(max_length=255)),
                ('TKT_REG_NO', models.CharField(max_length=255)),
                ('TKT_STATUS', models.IntegerField()),
                ('TKT_DATE', models.DateTimeField(auto_now=True)),
                ('TKT_TIME', models.DateTimeField(auto_now=True)),
                ('TKT_REMARKS', models.TextField(max_length=255)),
                ('TIME', models.DateTimeField(auto_now=True)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('REPORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'db_table': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='ReportFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RP_FILE_ID', models.CharField(max_length=255)),
                ('RP_FILE', models.ImageField(upload_to='reports')),
                ('TIME', models.DateTimeField(auto_now=True)),
                ('RP_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'db_table': 'Report Files',
            },
        ),
    ]
