# Generated by Django 3.2 on 2021-05-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='RP_ID',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='RP_REG_NO',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reportfiles',
            name='RP_FILE_ID',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='TKT_ID',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='TKT_REG_NO',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
