# Generated by Django 3.2 on 2021-05-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210506_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportfiles',
            old_name='RP_ID',
            new_name='Report',
        ),
    ]
