# Generated by Django 3.2 on 2021-05-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('reports', '0003_rename_rp_id_reportfiles_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='RP_PRIORITY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.priority'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='TKT_STATUS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.ticketstatus'),
        ),
    ]
