# Generated by Django 3.2 on 2021-05-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PT_ID',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
