# Generated by Django 3.2 on 2021-05-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_pt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='PT_HSTY_ID',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patienthistoryfiles',
            name='PT_HSTY_FILE_ID',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
