# Generated by Django 3.2 on 2021-05-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210506_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistoryfiles',
            name='PT_HSTY_ID',
        ),
        migrations.AddField(
            model_name='patienthistoryfiles',
            name='PatientHistory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.patienthistory'),
            preserve_default=False,
        ),
    ]
